name: "menu"
version: "1.1"
main: me.marvin.menu.standalone.StandaloneMenuBootstrap
author: marvin
website: https://github.com/marvintheskid/menu
description: A simplistic Bukkit GUI / Menu API using the InventoryHolder interface.
